config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "splash_screens#index"

  resources :groups, only: [:index, :show, :create, :destroy, :new] do
    resources :entities, only: [:index, :create, :new, :destroy] do
      resource :group_entities, only: [:create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :group_entities, dependent: :destroy
  has_many :groups, through: :group_entities

  # validations
  validates :name, presence: true, allow_blank: false
  validates :amount, presence: true, allow_blank: false,
                     numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :group_entities, dependent: :destroy
  has_many :entities, through: :group_entities

  # validations
  validates :name, presence: true, allow_blank: false
  validates :icon, presence: true, allow_blank: false
end

app/models/group_entity.rb
class GroupEntity < ApplicationRecord
  belongs_to :entity, foreign_key: 'entity_id', class_name: 'Entity'
  belongs_to :group, foreign_key: 'group_id', class_name: 'Group'

  validates :group, presence: true
  validates :entity, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :entities, foreign_key: 'author_id', dependent: :destroy
  has_many :groups, foreign_key: 'author_id', dependent: :destroy

  # validations
  validates :name, presence: true, allow_blank: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(_resource)
    groups_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:name, :email, :password)
    end

    devise_parameter_sanitizer.permit(:sign_in) do |user_params|
      user_params.permit(:email, :password, :remember_me)
    end
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_author

  def index
    @group = current_user.groups.find(params[:group_id])
    @entities = @group.entities.order(created_at: :desc)
  end

  def new
    @groups = current_user.groups.all
    @entity = Entity.new
  end

  # Take note that this is a many to many relationship
  def create
    @entity = Entity.new(entity_params) # do not use .create as it will save bu twe dont need that yet
    @entity.author_id = current_user.id
    if @entity.save
      @group_entities = GroupEntity.new(group_id: params[:group_id], entity_id: @entity.id)
      if @group_entities.save
        redirect_to group_entities_path(params[:group_id])
      else
        render :new
      end
    else
      render :new
    end
  end

  def destroy
    group = Group.find(params[:group_id]) # Find the group where that entity you are to destroy belongs
    @entity = group.entities.find(params[:id]) # Locate the all entities through the group it belongs
    entity = Entity.find(@entity.id) # Find the particular entity to destroy in Entity table through its id
    entity.group_entities.find_by(entity_id: entity.id).destroy
    @entity.destroy
    if @entity.destroy
      redirect_to group_entity_path, notice: 'Transaction deleted'
    else
      render :new
    end
  end

  private

  def set_author
    @author = current_user
  end

  def group_params
    params.require(:entity).permit(:id)
  end

  def entity_params
    params.permit(:name, :amount)
  end
end

app/controllers/group_entities_controller.rb
class GroupEntitiesController < ApplicationController
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_author

  def index
    @groups = Group.all.includes(:entities).order(created_at: :desc)
  end

  def show
    @group = Group.find(params[:id])
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.author_id = current_user.id
    if @group.save
      redirect_to groups_path, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    if @group.destroy
      redirect_to groups_path
    else
      render :new
    end
  end

  private

  def set_author
    @author = current_user
  end

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/splash_screens_controller.rb
class SplashScreensController < ApplicationController
  def index
    render :index
  end

  def new; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/helpers/group_entities_helper.rb
module GroupEntitiesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/splash_screens_helper.rb
module SplashScreensHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/entities/index.html.erb
<%= render "shared/navbara", {text:"Transactions", path: root_path, visible:"invisible"} %>

<section class="container-fluid tranSec">
  <div class="card mb-3 mt-3">
    <div class="card-body">
      <div class="row d-flex align-items-center">
        <div class="col-3">
          <img src="<%= @group.icon%>" class="img-fluid" alt="...">
        </div>
        <div class="col-5">
          <h1 class="card-text opacity-50 tacname"><%= @group.name %></h1>
        </div>
      </div>
    </div>
    <div class="card-footer d-flex justify-content-between align-items-center">
      <p class="card-text mb-0"><small class="text-muted">TOTAL PAYMENT</small></p>
      <p class="card-text mb-0">
      <small class="small_total_amout">
        <% credit = 0 %>
        <% @entities.each do |entity| %>
          <% total_entities = @entities.count %>
            <% credit += entity.amount.to_f %>
        <% end %>
        <%= "$#{credit}" %>
      </small>
      </p>
    </div>
  </div>

  <div class="card container-fluid p-2 mb-2 h-50 overflow-auto">
    <% @entities.each do |entity| %>
      <div class="card mb-4 w-80">
        <div class="card-body mb-2">
          <div class="d-flex " style="flex-direction: column; gap: 20px">
            <div class="col-3 d-flex w-100 justify-content-between">
              <div class="card-text fs-5 text-capitalize"><%= entity.name%></div>
              <div class="card-text fs-5">$<%= entity.amount.to_f%></div>
            </div>
            <span class="line" style="border-bottom: 1px solid black; width: 100%; opacity: 0.2;"></span>
            <div class="col-5 d-flex w-100 justify-content-between">
              <div class="card-text mb-0" style="font-size: 10px;">
                <% time = entity.created_at %>
                <%= time.strftime("%Y-%m-%d")%><br>
                <%= time.strftime("%H:%M:%S")%>
              </div>
              <div class="del-btn">
              <%= button_to group_entity_path(group_id: @group.id, id: entity.id), class:"btn", method: :delete do %>
                <i class="fa fa-trash text-danger"></i>
              <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class= "col-9">
    <%= link_to 'Add New Transaction', new_group_entity_path(params[:group_id]), class: 'btn btn-primary' %>
  </div>
<section>

app/views/entities/new.html.erb
<%= render "shared/navbara", {text:"Add Transaction", path: root_path, visible:"invisible"} %>
<%= form_with model: @group_entity, url: group_entities_path, method: :post do |f| %>
  <div class="card">
    <div class="card-body">

      <div class="mb-3">
        <%= f.label :name, { class: "form-label"} %>
        <%= f.text_field :name, { class: "form-control", autofocus: true, autocomplete: "name" } %>
      </div>

      <div class="mb-3">
        <%= f.label :amount %><br />
        <%= f.text_field :amount, { class: "form-control", autocomplete: "current-amount" } %>
      </div>

      <div class="actions">
        <%= f.submit "Add Transaction", data: {turbo: false}, class:"btn btn-primary" %>
      </div>

    </div>
  </div>
<% end %>

app/views/groups/index.html.erb
<%= render "shared/navbar", {text:"Categories", path: root_path, visible:"invisible"} %>
<div class="card cardmain">
  <div class="container mt-3">
    <% @groups.each do |group| %>
      <div class="card mb-3">
        <%= link_to group_entities_path(group.id), class:"nav-link" do %>
          <div class="card-body">
            <div class="row d-flex align-items-center gap-8">
              <div class="col-3 p-0">
                <img src="<%= group.icon%>" class="img-fluid" alt="...">
              </div>
              <div class="col-5 p-0 fs-5">
                <p class="card-text text-center categorytitle"><%= group.name %></p>
              </div>
              <div class="col-4">
                <p class="card-text fw-bold text-end w-10 amounts">
                  <small>
                    <% entities = group.entities %>
                    <% sum = 0 %>
                    <% entities.each do |entity| %>
                      <% sum += entity.amount.to_i %>
                    <% end %>
                    <%= "$#{sum}" %>
                  </small>
                </p>
              </div>
            </div>
          </div>
        <% end %>
        <div class="card-footer d-flex justify-content-between align-items-center">
          <p class="card-text">
            <small class="text-muted">
              <% time = group.created_at %>
              <%= time.strftime("%Y-%m-%d")%><br>
              <i class="fa-solid fa-calendar"></i>
              <i class="fa-solid fa-timer"></i>
              <%= time.strftime("%H:%M:%S")%>
            </small>
          </p>
          <%= button_to group_path(group.id), class:"btn", method: :delete do %>
            <i class="fa-solid fa-trash-can"></i>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <section class="bg-primary shadow text-center text-white p-2 mt-4 position-relative bottom-0 w-100">
    <%= link_to new_group_path,class: "nav-link" do %>
    <p class="my-3 p-1 text-white fs-3">Add New Category</p>
    <% end %>
  </section>
</div>

app/views/groups/new.html.erb
<%= render "shared/navbara", {text:"Add Category", path: root_path, visible:"invisible"} %>

<%= form_with model: @group, url: groups_path, method: :post do |f| %>
  <div class="card">
    <div class="card-body">

      <div class="mb-3">
        <%= f.text_field :name, { class: "form-control", autocomplete: "Category", placeholder: "Category" } %>
      </div>

      <div class="mb-3">
        <%= f.text_field :icon, { class: "form-control", autocomplete: "Icon url", placeholder: "Url" } %>
      </div>

      <div class="actions">
        <%= f.submit "Add Category", data: {turbo: false}, class:"btn btn-primary" %>
      </div>

    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,700,1,200" />

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert"><%= alert %></p>
    <% end %>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/js/all.min.js" integrity="sha512-Tn2m0TIpgVyTzzvmxLNuqbSJH3JP8jm+Cy3hvHrW7ndTDcJ1w5mBiksqDBb8GpE2ksktFvDB/ykZ0mDpsZj20w==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://kit.fontawesome.com/e5894c3c79.js" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_nav_login_signup.html.erb
<nav class="navbar  register">
  <div class="container-fluid">
    <div class="fluid-container login w-100">
      <div class="row w-100">
        <h2 class="py-3 text-center text-white"><%= text %></h2>
      </div>
    </div>
    <div class= "fluid-container singup d-flex position-absolute left-0 justify-content-center top-2">
      <%= link_to root_path, class: "button-17" do %>
        <span class="material-symbols-outlined">navigate_before</span>
      <% end %>
    </div>
  </div>
</nav>

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>
    <nav class="navbar  register">
      <div class="container-fluid">
        <div class="fluid-container login w-100">
          <div class="row w-100">
            <h2 class="py-3 text-center text-white">Categories</h2>
          </div>
        </div>
        <div class="d-flex position-absolute left-0">
          <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-link p-1 btn-sm text-white text-decoration-none" %>
        </div>
      </div>
    </nav>
<% end %>

app/views/shared/_navbara.html.erb
<% if user_signed_in? %>
    <nav class="navbar  register">
      <div class="container-fluid">
        <div class="fluid-container login w-100">
          <div class="row w-100">
            <h2 class="py-3 text-center text-white"><%= text %></h2>
          </div>
        </div>
        <div class= "fluid-container singup d-flex position-absolute left-0 justify-content-center top-2">
          <%= link_to groups_path, class: "button-17" do %>
            <span class="material-symbols-outlined">navigate_before</span>
          <% end %>
        </div>
      </div>
    </nav>
<% end %>

app/views/splash_screens/index.html.erb
<div class="card border-light w-100 vh-100 login-cad">
  <div class="card-body d-flex justify-content-center flex-column">
    <h5 class="card-title mt-3 mb-4 p-5 text-center fw-semibold">WELCOME TO BUDGET APP</h5>
    <%= link_to 'Log In', user_session_path, class: "button-71" %> 
    <%= link_to 'Sign Up', new_user_registration_path, class: "button-71" %>
  </div>
</div>